### PR TITLE
Add additional AutoDelete options

### PR DESCRIPTION
**Pull request by webOSpinn**
Add additional AutoDelete options so tasks that are occur less frequently remain in the completed list longer.

I have tasks that occur once a year and I would like them to remain in the completed list until the next occurrence of the task is completed. Because of this I've kept the AutoDelete option set to "None" but unfortunately there is no good way to cleanup really old tasks. Extending the AutoDelete option resolves this issue.

### CODE REVIEW

**Comment by japf** [comment]
That looks awesome, thank you for submitting the PR 👍 

May I ask how did you get the translations?

**Comment by webOSpinn** [comment]
I'm glad I can help improve the app I depend on everyday 😊 



I used Google Translate. I double checked the translations and they appeared to match what was already in the resx files for the translation of 3 months.

**Comment by japf** [comment]
Thank you for the PR !

I plan to ship a 4.8.6 version to the store over the week-end.

**Comment by webOSpinn** [comment]
Cool. I look forward to it. 

Congratulations on the new job and thank you for releasing the 2Day source code!

**Pull request merged**
