### PR TITLE
Update min and target version

### LINKED ISSUE #4: Review min and target version
The UWP app as now 10240 as min version and 10586 as target version. We should upgrade that so much newer version.

The min version could be Creators Update (15063) and the target version Fall Creators Update (16299).

While working on this issue, make sure the styles in the app are still compatible. I did investigations a while ago and moving to a more recent target was causing some UI glitches in the sidebar.

### PR DESCRIPTION
**Pull request by webOSpinn**
Fixes #4 
Update the min version to Creators Update (15063) and the target version to Fall Creators Update (16299).

### CODE REVIEW

**Comment by japf** [comment]
Thank you for the contribution.

It looks like this change is causing some small regression:

* the focus style seems to be broken in some part of the app like on the calendar:

image

* the style of the searchbox seems weird as well:

image

Any chance you can have a look?

**Comment by webOSpinn** [comment]
Sorry I must have missed those styling issues when I spot checked the app.



I'll take a look.

**Comment by webOSpinn** [comment]
I haven't forgotten about this. It has just been a crazy year. Among other things, I've had to swap out the hard drive on my dev machine twice and I just finally got Visual Studio working again after several re-installs.

I'll be honest, XAML styling is not my strength but it looks to me like the one issue might be caused by the lack of a style on the searchbox. I'm not really sure where to go from here? Should I be overriding just the `PointerOver` visual state on this instance of the control? Making it use the `ModernAutoSuggestBoxStyle` resulted in a very large textbox.

**Comment by webOSpinn** [comment]
I was looking at this again today. These are my notes so I don't forget them the next time I have a chance to look at things.

Here is what the search box is supposed to look like.
This is normal and on hover:
On hover
This is when it has focus:
Focus
This is when typing:
Typing
This is with text and not focused:
Not Focused

This is what happens when I give it the `ModernAutoSuggestBoxStyle`
ModernAutoSuggestBoxStyle

I did a little more digging and tried to make a style based on `AutoSuggestBoxTextBoxStyle` with just the `PointerOver` visual state modified per this post:
https://stackoverflow.com/questions/45980124/uwp-autosuggestbox-queryicon-disappears-after-style-added
This is what it looks like normally:
Normal
On hover:
Hover
This is when typing:
Typing
This is with text and not focused:
Not Focused
I guess this shows that without any styling the search box is getting the default styling of the `AutoSuggestBox`

**Pull request closed without merging**
